version: 2

jobs:
  "test_unit":
    docker: &DOCKERIMAGE
      - image: jenkinsrise/cci-v2-launcher-electron:0.0.6
    steps:
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: node-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          command: npm run test
          no_output_timeout: 1m

  "test_integration":
    docker: *DOCKERIMAGE
    steps:
      - run: sudo apt-get -y update || true
      - run: sudo apt-get -y upgrade || true
      - run: sudo apt-get -y install libgtk-3-0
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: node-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          command: npm run ci-integration
          no_output_timeout: 1m

  "build":
    docker: *DOCKERIMAGE
    steps:
      - checkout
      - restore_cache:
          key: node-cache-prod-{{ checksum "package.json" }}
      - run: ./build.sh
      - save_cache:
          key: node-cache-prod-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - build

  "stage":
    docker: *DOCKERIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm install common-display-module
      - run:
          name: Stage
          command: node_modules/common-display-module/stage.sh
          environment:
            MODULENAME: player-electron
      - persist_to_workspace:
          root: .
          paths:
            - version

  "e2e":
    docker: *DOCKERIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: echo "version $(cat version)"
      - run: echo "no e2e yet"

  "deploy-beta":
    docker: *DOCKERIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm install common-display-module
      - restore_cache:
          key: node-cache-prod-{{ checksum "package.json" }}
      - run:
          name: Deploy to beta
          command: node_modules/common-display-module/deploy.sh
          environment:
            MODULENAME: player-electron

  "deploy-stable":
    docker: *DOCKERIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-prod-{{ checksum "package.json" }}
      - run: npm install common-display-module
      - run:
          name: Deploy to stable
          command: node_modules/common-display-module/deploy.sh
          environment:
            BRANCH: STABLE
            MODULENAME: player-electron

workflows:
  version: 2
  workflow1:
    jobs:
      - "test_unit"
      - "test_integration"
      - "build":
          filters:
            branches:
              only:
                - master
                - build/stable
                - /^stage\/.*/
                - /^staging\/.*/
      - "stage":
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - build/stable
                - /^stage\/.*/
                - /^staging\/.*/
      - "e2e":
          requires:
            - test_unit
            - test_integration
            - stage
          filters:
            branches:
              only:
                - master
                - build/stable
      - "deploy-stable":
          requires:
            - e2e
          filters:
            branches:
              only:
                - build/stable

      - "deploy-beta":
          requires:
            - e2e
          filters:
            branches:
              only:
                - master
